# -*- coding: utf-8 -*-
"""CarPricePrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDKrezjOA8hDBcrtRJQaBcehXEU26loN
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

# Load data
df = pd.read_csv("ford.csv")

# Basic inspection
print(df.head())
print(df.shape)
df.info()
print(df.describe())
print(df.isnull().sum())

# -----------------------------
# EDA
# -----------------------------

sns.histplot(df['price'], bins=50, kde=True)
plt.show()

sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.show()

sns.boxplot(data=df, x='year', y='price')
plt.xticks(rotation=90)
plt.show()

sns.scatterplot(data=df, x='mileage', y='price')
plt.show()

sns.boxplot(data=df, x='engineSize', y='price')
plt.show()

sns.boxplot(data=df, x='transmission', y='price')
plt.show()

sns.boxplot(data=df, x='fuelType', y='price')
plt.show()

sns.boxplot(data=df, x='model', y='price')
plt.xticks(rotation=90)
plt.show()


# -----------------------------
# X and y
# -----------------------------

X = df.drop(columns=['price'])
y = df['price']


# -----------------------------
# ONE-HOT ENCODING
# -----------------------------

X_one_encode = pd.get_dummies(
    X,
    columns=['model', 'transmission', 'fuelType'],
    drop_first=True
)

X_one_encode = X_one_encode.astype(float)


# -----------------------------
# SCALING
# -----------------------------

from sklearn.preprocessing import StandardScaler

numerical_cols = [
    'year',
    'mileage',
    'tax',
    'mpg',
    'engineSize'
]

scaler = StandardScaler()

X_one_encode[numerical_cols] = scaler.fit_transform(
    X_one_encode[numerical_cols]
)


# -----------------------------
# TRAIN TEST SPLIT
# -----------------------------

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_one_encode,
    y,
    test_size=0.33,
    random_state=42
)


# -----------------------------
# LINEAR REGRESSION
# -----------------------------

from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))


# -----------------------------
# ADJUSTED R2
# -----------------------------

r2 = r2_score(y_test, y_pred)

n = X_test.shape[0]
p = X_test.shape[1]

adjusted_r2 = 1 - ((1-r2) * (n-1)) / (n-p-1)

print("Adjusted R2 Score:", adjusted_r2)